// <auto-generated />
using System;
using Fintacharts.AssetTracker.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fintacharts.AssetTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fintacharts.AssetTracker.Infrastructure.Persistence.Entities.AssetPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Ask")
                        .HasColumnType("numeric")
                        .HasColumnName("ask");

                    b.Property<decimal>("Bid")
                        .HasColumnType("numeric")
                        .HasColumnName("bid");

                    b.Property<string>("InstrumentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instrument_id");

                    b.Property<decimal>("Last")
                        .HasColumnType("numeric")
                        .HasColumnName("last");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_asset_prices");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("ix_asset_prices_instrument_id");

                    b.ToTable("asset_prices", (string)null);
                });

            modelBuilder.Entity("Fintacharts.AssetTracker.Infrastructure.Persistence.Entities.Instrument", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symbol");

                    b.HasKey("Id")
                        .HasName("pk_instruments");

                    b.ToTable("instruments", (string)null);
                });

            modelBuilder.Entity("Fintacharts.AssetTracker.Infrastructure.Persistence.Entities.AssetPrice", b =>
                {
                    b.HasOne("Fintacharts.AssetTracker.Infrastructure.Persistence.Entities.Instrument", "Instrument")
                        .WithMany("Prices")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asset_prices_instruments_instrument_id");

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("Fintacharts.AssetTracker.Infrastructure.Persistence.Entities.Instrument", b =>
                {
                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
